<?php echo $this->doctype(); ?>

<html lang="pt-br" ng-app="AdminApp">
    <head>
        <base href="/admin/">
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF-Base Administração')
            ->setSeparator(' - ')->setAutoEscape(false) ?>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/octicons/3.1.0/octicons.min.css">

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!--[if lt IE 9]>
          <script src="https://cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="https://cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
          $.widget.bridge('uibutton', $.ui.button);
        </script>
        <script src="https://cdn.jsdelivr.net/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('static/libs/AdminLTE/dist/css/skins/skin-black.min.css'))
                        ->prependStylesheet($this->basePath('static/libs/AdminLTE/dist/css/AdminLTE.min.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/static/js/admin/acl/privilege/privilege.controller.js')
            ->prependFile($this->basePath() . '/static/js/admin/acl/resource/resource.controller.js')
            ->prependFile($this->basePath() . '/static/js/admin/acl/role/role.controller.js')
            ->prependFile($this->basePath() . '/static/js/admin/dashboard/dashboard.controller.js')
            ->prependFile($this->basePath() . '/static/js/admin/app.js')
            ->prependFile($this->basePath() . '/static/libs/angular-sanitize/angular-sanitize.min.js')
            ->prependFile($this->basePath() . '/static/libs/angular-route/angular-route.min.js')
            ->prependFile($this->basePath() . '/static/libs/angular-resource/angular-resource.min.js')
            ->prependFile($this->basePath() . '/static/libs/angular-mocks/angular-mocks.js')
            ->prependFile($this->basePath() . '/static/libs/angular/angular.min.js')
            ->prependFile($this->basePath('static/libs/AdminLTE/dist/js/app.min.js')); ?>
    </head>
    <body class="hold-transition skin-black sidebar-mini">
        <div class="wrapper">
            <header class="main-header">
                <!-- Logo -->
                <a href="#" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>ZF</b></span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>ZF2</b>-base</span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <li><a href="#">Exemplo</a></li>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form>
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="header">MAIN NAVIGATION</li>
                        <li class="active">
                            <a href="/admin">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-buysellads"></i><span>Acl</span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="acl/roles"><i class="fa fa-circle-o"></i> Roles</a></li>
                                <li><a href="acl/resources"><i class="fa fa-circle-o"></i> Resources</a></li>
                                <li><a href="acl/privileges"><i class="fa fa-circle-o"></i> Privileges</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper" ng-view>

            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 0.0.1
                </div>
                <strong>ZF-base admin</strong>
            </footer>

            <!-- Control Sidebar -->
            <aside class="control-sidebar control-sidebar-dark">
                <!-- Create the tabs -->
                <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                    <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
                    <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
                </ul>
            </aside>
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
               immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>
    </body>
</html>
